[project]
name = "seguridad-keylogger"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pynput>=1.8.1",
	#    "pywin32=latest"
]
